---
# tasks file for docker_base
# start all needed base container

- name: '{{ app_name }} | include nextcloud vars'
  include_vars: "{{ item }}"
  loop:
    - group_vars/traefik.yml
    - group_vars/nextcloud.yml

- name: '{{ app_name }} | include directory structure'
  include_tasks: directory_structure.yml

- name: '{{ app_name }} | nextcloud network'
  include_tasks: tasks/network.yml

- name: define db to create
  set_fact: 
    app_db_create_name: "{{ 'default' if (app_db_type == 'pgsql') else app_db_name }}"

- name: '{{ app_name }} | docker database'
  include_tasks: create_app_{{ app_db_type }}_container.yml
  vars:
    app_db_name: "{{ app_db_create_name }}"

- name: '{{ app_name }} | docker redis'
  include_tasks: redis.yml

- name: '{{ app_name }} | docker nextcloud'
  include_tasks: nextcloud.yml

- name: '{{ app_name }} | docker collabora'
  include_tasks: collabora.yml
  when: site_item.collabora|bool

- name: '{{ app_name }} | docker onlyoffice'
  include_tasks: onlyoffice.yml
  when: site_item.onlyoffice|bool

- name: '{{ app_name }} | docker nginx'
  include_tasks: nginx.yml
  when: "'fpm' in docker_nextcloud_image"

- name: '{{ app_name }} | configure nextcloud'
  include_tasks: config.yml

- name: '{{ app_name }} | backup nextcloud'
  include_tasks: tasks/backup_script.yml
  when: backup_enabled|bool

- name: '{{ app_name }} | clear app_passwd'
  set_fact: app_passwd=''